services:
- docker
dist: xenial

git:
  submodules: false

install:
  - sudo add-apt-repository ppa:projectatomic/ppa
  - sudo apt-get update
  - sudo wget -O /etc/containers/registries.conf https://gist.githubusercontent.com/JBBgameich/d5d8d683eea994ba7576f0265ce5f4b3/raw/675af53056f80a0f197d3cf608939847a3dcff43/registries.conf
  - sudo apt-get install podman

script: bash travis_docker.sh build

deploy:
  provider: script
  script: bash docker/travis_docker.sh push
  on:
    branch: master

matrix:
  include:
    - env: ARCH=amd64
    - env: ARCH=armhf
    - env: ARCH=arm64
