services:
- docker
os: linux
language: shell
dist: bionic

git:
  submodules: false

install:
  - sudo apt update
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

  # Fetch keyring
  - echo "deb [trusted=yes] http://deb.debian.org/debian testing main" |sudo tee /etc/apt/sources.list.d/debian.list
  - sudo apt-get -qq update
  - sudo apt-get install debian-archive-keyring gnupg -y
  - echo "deb http://deb.debian.org/debian testing main" |sudo tee /etc/apt/sources.list.d/debian.list

  - sudo apt update
  - sudo apt install qemu-user-static binfmt-support docker-ce -y
  - update-binfmts --display

script: bash docker/travis_docker.sh build

deploy:
  provider: script
  script: bash docker/travis_docker.sh push
  on:
    branch: master

jobs:
  include:
    - env: ARCH=amd64
    - env: ARCH=armhf
    - env: ARCH=arm64
    - env: ARCH=i386

    # For gemian
    #- env: DIST=buster ARCH=arm64
