services:
- docker
dist: bionic

git:
  submodules: false

install:
  - sudo apt update
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt install dpkg debian-archive-keyring -y
  - echo "deb [trusted=yes] http://deb.debian.org/debian testing main" |sudo tee -a /etc/apt/sources.list
  - sudo apt update
  - sudo apt install qemu-user-static binfmt-support docker-ce -y
  - update-binfmts --display

script: bash docker/travis_docker.sh build

deploy:
  provider: script
  script: bash docker/travis_docker.sh push
  on:
    branch: master

matrix:
  include:
    - env: ARCH=amd64
    - env: ARCH=armhf
    - env: ARCH=arm64
    - env: ARCH=i386
