version: 2
jobs:
  build:
    docker:
      - image: debian:testing
    steps:
      - checkout
      - run:
          name: apt cache update
          command: apt update
      - run:
          name: dependency installation
          command: apt install make devscripts -y
      - run:
          name: test package setup
          command: make plasma-mobile mainline halium
