# To use this in a package, use
# include: 'https://gitlab.com/debian-pm/tools/build/raw/master/docker/gitlab-ci-base.yml'

cache:
  paths:
    - ../ccache/

before_script:
  - apt update

variables:
  REPO_BRANCH: "master"

build:source:
  stage: build
  script: /usr/bin/ci-build source
  image: jbbgameich/build:latest-amd64

build:amd64:
  stage: build
  script: /usr/bin/ci-build binary
  image: jbbgameich/build:latest-amd64
  tags:
    - amd64

build:i386:
  stage: build
  script: /usr/bin/ci-build binary
  image: jbbgameich/build:latest-i386
  tags:
    - i386

build:armhf:
  stage: build
  script: /usr/bin/ci-build binary
  image: jbbgameich/build:latest-armhf
  tags:
    - armhf

build:arm64:
  stage: build
  script: /usr/bin/ci-build binary
  image: jbbgameich/build:latest-arm64
  tags:
    - arm64
