# To use this in a package, use
# include: 'https://gitlab.com/debian-pm/tools/build/raw/master/docker/gitlab-ci-base.yml'

before_script:
  - apt update

variables:
  - REPO_BRANCH: "master"

build:amd64:
  stage: build
  script: /usr/bin/ci-build
  image: jbbgameich/build:latest-amd64
  tags:
    - gitlab-org

build:i386:
  stage: build
  script: /usr/bin/ci-build
  image: jbbgameich/build:latest-i386
  tags:
    - gitlab-org

build:armhf:
  stage: build
  script: /usr/bin/ci-build
  image: jbbgameich/build:latest-armhf
  tags:
    - armhf

build:arm64:
  stage: build
  script: /usr/bin/ci-build
  image: jbbgameich/build:latest-arm64
  tags:
    - arm64
