# To use this in a package, use
# include: 'https://gitlab.com/debian-pm/tools/build/raw/master/docker/gitlab-ci-base.yml'

cache:
  paths:
    - debian/ccache/amd64
    - debian/ccache/arm64
    - debian/ccache/arm64-caf
    - debian/ccache/i386
    - debian/ccache/armhf
    - debian/ccache/armhf-caf

build:source:
  stage: build
  script:
    - /usr/local/bin/ci-config
    - /usr/local/bin/ci-build source
  image: registry.gitlab.com/debian-pm/tools/build:testing-amd64

build:amd64:
  stage: build
  script:
    - /usr/local/bin/ci-config
    - /usr/local/bin/ci-build binary
  image: registry.gitlab.com/debian-pm/tools/build:testing-amd64

#build:i386:
#  stage: build
#  script:
#    - /usr/local/bin/ci-config
#    - /usr/local/bin/ci-build binary
#  image: registry.gitlab.com/debian-pm/tools/build:testing-i386

#build:armhf:
#  stage: build
#  script:
#    - /usr/local/bin/ci-config
#    - /usr/local/bin/ci-build binary
#  image: registry.gitlab.com/debian-pm/tools/build:testing-armhf
#  tags:
#    - armhf

build:arm64:
  stage: build
  script:
    - /usr/local/bin/ci-config
    - /usr/local/bin/ci-build binary
  image: registry.gitlab.com/debian-pm/tools/build:testing-arm64
  tags:
    - arm64
