build:armhf-caf:
  stage: build
  script:
    - /usr/bin/ci-config caf
    - /usr/bin/ci-build binary
  image: jbbgameich/build:latest-armhf
  tags:
    - armhf
  variables:
    REPO_BRANCH: "caf"
    DEB_BUILD_PROFILES: "caf"

build:arm64-caf:
  stage: build
  script:
    - /usr/bin/ci-config caf
    - /usr/bin/ci-build binary
  image: jbbgameich/build:latest-arm64
  tags:
    - arm64
  variables:
    REPO_BRANCH: "caf"
    DEB_BUILD_PROFILES: "caf"
