build:armhf-caf:
  stage: build
  script:
    - /usr/local/bin/ci-config
    - /usr/local/bin/ci-build binary
  image: registry.gitlab.com/debian-pm/tools/build:testing-armhf
  tags:
    - armhf
  variables:
    REPO_COMPONENT: "caf"
    DEB_BUILD_PROFILES: "caf"

build:arm64-caf:
  stage: build
  script:
    - /usr/local/bin/ci-config
    - /usr/local/bin/ci-build binary
  image: registry.gitlab.com/debian-pm/tools/build:testing-arm64
  tags:
    - arm64
  variables:
    REPO_COMPONENT: "caf"
    DEB_BUILD_PROFILES: "caf"
