#!/bin/bash
# 2009-04-09 tyler - use previously built packages as an apt source
# http://blog.edseek.com/~jasonb/articles/pbuilder_backports/pbuilderbuild.html#pbuilderhook

: ${DISTRIBUTION:=$(lsb_release --short --codename)}
: ${ARCH:=$(dpkg --print-architecture)}
NAME="$DISTRIBUTION-$ARCH-caf"
BUILDRESULT="/var/cache/pbuilder/$NAME/result/"

# create apt archive of previously built packages
( cd $BUILDRESULT ; apt-ftparchive packages . > $BUILDRESULT/Packages )

# see ~/.pbuilderrc for creation of $BUILDRESULT/Release

apt update
