#!/bin/sh

if ! grep "debpm" /etc/apt/sources.list; then
	# Add sourceline
	echo "deb https://repo.kaidan.im/debpm buster main" >> /etc/apt/sources.list

	# Download and install packaged keyring
	TEMP_DEB="$(mktemp)" &&
	wget -O "$TEMP_DEB" 'https://repo.kaidan.im/debpm/pool/main/d/debian-pm-keyring/debian-pm-archive-keyring_20181021_all.deb' &&
	dpkg -i "$TEMP_DEB"
	rm -f "$TEMP_DEB"

	# Update package lists
	apt update --allow-unauthenticated
fi
